export const DEPARTMENTS = {
  cse: {
    slug: "cse",
    short: "CSE",
    title: "Computer Science & Engineering (CSE)",
    subtitle: "Algorithms, systems, software engineering, and modern computing foundations.",
    program: { name: "B.Tech", duration: "4 Years", intake: "To be updated" },
    hod: { name: "To be updated", email: "To be updated" },
    about:
      "The Department of Computer Science & Engineering focuses on strong fundamentals in computing and modern software development practices. This content is a placeholder and can be replaced with the official department profile.",
    vision: "To be updated (official vision statement).",
    mission: ["To be updated (Mission 1).", "To be updated (Mission 2).", "To be updated (Mission 3)."],
    peos: ["To be updated (PEO-1).", "To be updated (PEO-2).", "To be updated (PEO-3)."],
    pos: ["To be updated (POs as per NBA/OBE)."],
    psos: ["To be updated (PSO-1).", "To be updated (PSO-2)."],
    highlights: [
      "Programming & DSA",
      "Operating Systems & Networks",
      "DBMS & Web Technologies",
      "Cloud & DevOps fundamentals",
    ],
    labs: [
      {
        name: "Programming Lab",
        desc: "Foundations of programming, problem-solving, and software development.",
        equipment: ["To be updated"],
      },
      {
        name: "Data Structures Lab",
        desc: "Implementation of core data structures and algorithmic problem solving.",
        equipment: ["To be updated"],
      },
      {
        name: "DBMS Lab",
        desc: "Database modelling, queries, transactions, and application integration.",
        equipment: ["To be updated"],
      },
      {
        name: "Computer Networks Lab",
        desc: "Networking fundamentals, routing, switching, and network programming basics.",
        equipment: ["To be updated"],
      },
    ],
    activities: ["Technical club events (to be updated)", "Hackathons/Workshops (to be updated)"],
    downloads: [
      { label: "Syllabus", href: "/syllabus" },
      { label: "Academic Calendar", href: "/calendar" },
    ],
    careers: [
      "Software Engineer / Full Stack Developer",
      "System / Network Engineer",
      "Cloud / DevOps Associate",
      "Competitive Programming & Research",
    ],
  },
  aiml: {
    slug: "aiml",
    short: "AI & ML",
    title: "AI & Machine Learning (AI & ML)",
    subtitle: "Deep learning, computer vision, NLP, and data-driven engineering.",
    program: { name: "B.Tech", duration: "4 Years", intake: "To be updated" },
    hod: { name: "To be updated", email: "To be updated" },
    about:
      "The Department of AI & Machine Learning builds data-driven thinking and modern AI fundamentals with practical exposure through projects and labs. Replace this placeholder with the official department profile.",
    vision: "To be updated (official vision statement).",
    mission: ["To be updated (Mission 1).", "To be updated (Mission 2).", "To be updated (Mission 3)."],
    peos: ["To be updated (PEO-1).", "To be updated (PEO-2).", "To be updated (PEO-3)."],
    pos: ["To be updated (POs as per NBA/OBE)."],
    psos: ["To be updated (PSO-1).", "To be updated (PSO-2)."],
    highlights: [
      "Machine Learning & Deep Learning",
      "Computer Vision & NLP",
      "Data Engineering basics",
      "Responsible AI basics",
    ],
    labs: [
      { name: "AI/ML Lab", desc: "Model building, training workflows, and experimentation.", equipment: ["To be updated"] },
      { name: "Data Science Lab", desc: "Data analysis, visualization, and applied ML pipelines.", equipment: ["To be updated"] },
      { name: "Compute Facility", desc: "GPU/compute resources (as available).", equipment: ["To be updated"] },
      { name: "Mini Project Lab", desc: "Project development and demos.", equipment: ["To be updated"] },
    ],
    activities: ["Project showcases (to be updated)", "AI workshops (to be updated)"],
    downloads: [
      { label: "Syllabus", href: "/syllabus" },
      { label: "Research", href: "/research" },
    ],
    careers: [
      "ML Engineer (entry-level)",
      "Data Analyst / Junior Data Scientist",
      "AI Research Intern",
      "M.Tech / Higher Studies",
    ],
  },
  ce: {
    slug: "ce",
    short: "CE",
    title: "Civil Engineering",
    subtitle: "Structures, geo-technical, transportation, and environmental engineering.",
    program: { name: "B.Tech", duration: "4 Years", intake: "To be updated" },
    hod: { name: "To be updated", email: "To be updated" },
    about:
      "The Department of Civil Engineering covers core areas of planning, design, construction, and sustainability. Replace this placeholder with the official department profile.",
    vision: "To be updated (official vision statement).",
    mission: ["To be updated (Mission 1).", "To be updated (Mission 2).", "To be updated (Mission 3)."],
    peos: ["To be updated (PEO-1).", "To be updated (PEO-2).", "To be updated (PEO-3)."],
    pos: ["To be updated (POs as per NBA/OBE)."],
    psos: ["To be updated (PSO-1).", "To be updated (PSO-2)."],
    highlights: [
      "Structural Analysis & Design",
      "Surveying & Geomatics",
      "Transportation Engineering",
      "Environmental Engineering",
    ],
    labs: [
      { name: "Survey Lab", desc: "Surveying instruments and field practice.", equipment: ["To be updated"] },
      { name: "Concrete & Material Testing Lab", desc: "Material testing and mix design practices.", equipment: ["To be updated"] },
      { name: "Geotechnical Lab", desc: "Soil testing and foundation engineering experiments.", equipment: ["To be updated"] },
      { name: "Environmental Engineering Lab", desc: "Water/wastewater basics and environmental studies.", equipment: ["To be updated"] },
    ],
    activities: ["Site visits (to be updated)", "Model making / workshops (to be updated)"],
    downloads: [
      { label: "Syllabus", href: "/syllabus" },
      { label: "Notices", href: "/notices" },
    ],
    careers: [
      "Site Engineer / QA-QC",
      "Structural Design (entry-level)",
      "Govt. Sector / PSU preparation",
      "Higher Studies & Research",
    ],
  },
  me: {
    slug: "me",
    short: "ME",
    title: "Mechanical Engineering",
    subtitle: "Thermal, manufacturing, design, and applied mechanics.",
    program: { name: "B.Tech", duration: "4 Years", intake: "To be updated" },
    hod: { name: "To be updated", email: "To be updated" },
    about:
      "The Department of Mechanical Engineering builds strong fundamentals in design, manufacturing, and thermal sciences with practical lab exposure. Replace this placeholder with the official department profile.",
    vision: "To be updated (official vision statement).",
    mission: ["To be updated (Mission 1).", "To be updated (Mission 2).", "To be updated (Mission 3)."],
    peos: ["To be updated (PEO-1).", "To be updated (PEO-2).", "To be updated (PEO-3)."],
    pos: ["To be updated (POs as per NBA/OBE)."],
    psos: ["To be updated (PSO-1).", "To be updated (PSO-2)."],
    highlights: [
      "Thermodynamics & Heat Transfer",
      "Manufacturing Processes",
      "Machine Design",
      "CAD/CAM basics",
    ],
    labs: [
      { name: "Thermal Engineering Lab", desc: "Thermal systems experiments and measurements.", equipment: ["To be updated"] },
      { name: "Manufacturing / Workshop", desc: "Hands-on workshop practice and manufacturing basics.", equipment: ["To be updated"] },
      { name: "CAD Lab", desc: "CAD modelling and engineering drawing tools.", equipment: ["To be updated"] },
      { name: "Metrology Lab", desc: "Measurements, tolerances, and quality inspection basics.", equipment: ["To be updated"] },
    ],
    activities: ["Workshops (to be updated)", "Industrial visits (to be updated)"],
    downloads: [
      { label: "Syllabus", href: "/syllabus" },
      { label: "Placements", href: "/placement" },
    ],
    careers: [
      "Production / Maintenance Engineer",
      "Design Engineer (entry-level)",
      "Automotive & Core Mechanical",
      "Higher Studies / GATE",
    ],
  },
  aero: {
    slug: "aero",
    short: "AERO",
    title: "Aeronautical Engineering",
    subtitle: "Aerodynamics, propulsion, aircraft structures, and flight technologies.",
    program: { name: "B.Tech", duration: "4 Years", intake: "To be updated" },
    hod: { name: "To be updated", email: "To be updated" },
    about:
      "The Department of Aeronautical Engineering introduces core aerospace concepts and engineering fundamentals with design-oriented learning and projects. Replace this placeholder with the official department profile.",
    vision: "To be updated (official vision statement).",
    mission: ["To be updated (Mission 1).", "To be updated (Mission 2).", "To be updated (Mission 3)."],
    peos: ["To be updated (PEO-1).", "To be updated (PEO-2).", "To be updated (PEO-3)."],
    pos: ["To be updated (POs as per NBA/OBE)."],
    psos: ["To be updated (PSO-1).", "To be updated (PSO-2)."],
    highlights: [
      "Aerodynamics fundamentals",
      "Aircraft Structures",
      "Propulsion basics",
      "Flight Mechanics basics",
    ],
    labs: [
      { name: "Aerodynamics Lab", desc: "Aerodynamics experiments (as available).", equipment: ["To be updated"] },
      { name: "Structures / Materials Lab", desc: "Material properties and structures basics.", equipment: ["To be updated"] },
      { name: "CAD / Design Lab", desc: "Design tools for aircraft modelling basics.", equipment: ["To be updated"] },
      { name: "Project & Model Lab", desc: "Prototype/model building and project showcase.", equipment: ["To be updated"] },
    ],
    activities: ["Model/Aeromodelling activities (to be updated)", "Seminars (to be updated)"],
    downloads: [
      { label: "Syllabus", href: "/syllabus" },
      { label: "Research", href: "/research" },
    ],
    careers: [
      "Aerospace / Aviation (entry-level roles)",
      "Design & Analysis (entry-level)",
      "Defence sector preparation",
      "Higher Studies & Research",
    ],
  },
  eee: {
    slug: "eee",
    short: "EEE",
    title: "Electrical & Electronics Engineering (EEE)",
    subtitle: "Power systems, control, machines, and core electronics.",
    program: { name: "B.Tech", duration: "4 Years", intake: "To be updated" },
    hod: { name: "To be updated", email: "To be updated" },
    about:
      "The Department of Electrical & Electronics Engineering covers core electrical engineering with exposure to machines, power systems, and control. Replace this placeholder with the official department profile.",
    vision: "To be updated (official vision statement).",
    mission: ["To be updated (Mission 1).", "To be updated (Mission 2).", "To be updated (Mission 3)."],
    peos: ["To be updated (PEO-1).", "To be updated (PEO-2).", "To be updated (PEO-3)."],
    pos: ["To be updated (POs as per NBA/OBE)."],
    psos: ["To be updated (PSO-1).", "To be updated (PSO-2)."],
    highlights: [
      "Electrical Machines",
      "Power Systems & Protection",
      "Control Systems",
      "Power Electronics basics",
    ],
    labs: [
      { name: "Electrical Machines Lab", desc: "DC/AC machines experiments and characteristics.", equipment: ["To be updated"] },
      { name: "Power Electronics Lab", desc: "Converters, inverters, and drives basics.", equipment: ["To be updated"] },
      { name: "Control Systems Lab", desc: "Control experiments and system response studies.", equipment: ["To be updated"] },
      { name: "Measurements & Instrumentation Lab", desc: "Measuring instruments and instrumentation basics.", equipment: ["To be updated"] },
    ],
    activities: ["Workshops (to be updated)", "Industrial visits (to be updated)"],
    downloads: [
      { label: "Syllabus", href: "/syllabus" },
      { label: "Placement", href: "/placement" },
    ],
    careers: [
      "Electrical Engineer (entry-level)",
      "Power Sector / Utilities",
      "Automation / Control (entry-level)",
      "Higher Studies / GATE",
    ],
  },
};

export const DEPARTMENT_LIST = Object.values(DEPARTMENTS);

export const SLUG_ALIASES = {
  "ai-ml": "aiml",
  "ai_ml": "aiml",
  "ai&ml": "aiml",
  "aiandml": "aiml",
  "ai-ml-engineering": "aiml",
  "artificial-intelligence": "aiml",
  "artificial-intelligence-and-ml": "aiml",
  "artificial-intelligence-and-machine-learning": "aiml",

  cse: "cse",
  "computer-science": "cse",
  "computer-science-engineering": "cse",
  "computer-science-and-engineering": "cse",

  aeronautical: "aero",
  "aeronautical-engineering": "aero",
  aeroengineering: "aero",

  mechanical: "me",
  machenical: "me",
  "mechanical-engineering": "me",
  mechanicalengineering: "me",
  mech: "me",

  civil: "ce",
  "civil-engineering": "ce",

  "electrical-and-electronics": "eee",
  "electrical-electronics": "eee",
  electrical: "eee",
  "electrical-engineering": "eee",
  "eee-department": "eee",
};      
