export const DEPARTMENTS = {
  cse: {
    slug: "cse",
    short: "CSE",
    title: "Computer Science & Engineering (CSE)",
    bannerImage: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?q=80&w=2070&auto=format&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?q=80&w=2070&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1542831371-29b0f74f9713?q=80&w=2070&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1518770660439-4636190af475?q=80&w=2070&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?q=80&w=2070&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1525547719571-a2d4ac8945e2?q=80&w=2070&auto=format&fit=crop"
    ],
    subtitle: "Outstanding learning environment for excellence in teaching and research.",
    program: { name: "B.Tech", duration: "4 Years", intake: "60" },
    hod: { name: "Dr. Kumari Priyanka Sinha", email: "hodcse@ncechandi.ac.in" },
    about:
      "The field of Computer Science and Engineering nowadays has become one of the most demandable branch amongst the aspiring engineers. We have a goal to provide an outstanding learning environment complemented by excellence in teaching. The Department is moving ahead to build technical platform to students by spreading awareness of technologies, transferring of the knowledge, sharpening the obtained knowledge, and exposing students to solve real time problems. Laboratories are fully equipped with latest computers and are supported by high speed Internet connection. Job opportunities are available both in private and public sectors for a graduate of this discipline. Subjects of further research include Artificial Intelligence especially Neural Network and Machine Learning and many more.",
    vision:
      "To become a centre of excellence in computer science and engineering by providing a holistic approach towards research, innovation, entrepreneurship and employability empowered with ethical values.",
    mission: [
      "M1: Mould the students to become Software Professionals, Researchers and Entrepreneurs by providing advanced laboratories.",
      "M2: Impart high quality professional training to get expertise in modern software tools and technologies to cater to the real time requirements of the industry.",
      "M3: Inculcate team work and lifelong learning among students with a sense of societal and ethical responsibilities.",
    ],
    peos: [
      "PEO1: Prepare graduates to have knowledge and skill to compete for career in computer science and engineering.",
      "PEO2: Well qualified to participate in research and innovation. Also serve the society with new ideas and be a long-life learner.",
      "PEO3: To train students with good knowledge along with practical efficiency in computer science to create novel products for the benefits of life.",
      "PEO4: Develop engineering design skill, problem solving skill and aptitude for innovation as they work individually and in multidisciplinary area.",
      "PEO5: Graduates will possess leadership qualities, work harmoniously as a team member with effective communication skills.",
    ],
    pos: [
      "PO1: Engineering knowledge",
      "PO2: Problem analysis",
      "PO3: Design/development of solutions",
      "PO4: Conduct investigations of complex problems",
      "PO5: Modern tool usage",
      "PO6: The engineer and society",
      "PO7: Environment and sustainability",
      "PO8: Ethics",
      "PO9: Individual and team work",
      "PO10: Communication",
      "PO11: Project management and finance",
      "PO12: Life-long learning",
    ],
    psos: [
      "PSO1: Foundation of mathematical concepts: To use mathematical methodologies to crack problem using suitable mathematical analysis, data structure and suitable algorithm.",
      "PSO2: Foundation of Computer System: the ability to interpret the fundamental concepts and methodology of computer systems. Students can understand the functionality of hardware and software aspects of computer systems.",
      "PSO3: Foundations of Software development: the ability to grasp the software development lifecycle and methodologies of software systems. Possess competent skills and knowledge of software design process. Familiarity and practical proficiency with a broad area of programming concepts and provide new ideas and innovations towards research.",
    ],
    highlights: [
      "Programming & DSA",
      "Operating Systems & Networks",
      "DBMS & Web Technologies",
      "Cloud & DevOps fundamentals",
    ],
    labs: [
      {
        name: "Programming Lab",
        desc: "Foundations of programming, problem-solving, and software development.",
        equipment: ["To be updated"],
      },
      {
        name: "Data Structures Lab",
        desc: "Implementation of core data structures and algorithmic problem solving.",
        equipment: ["To be updated"],
      },
      {
        name: "DBMS Lab",
        desc: "Database modelling, queries, transactions, and application integration.",
        equipment: ["To be updated"],
      },
      {
        name: "Computer Networks Lab",
        desc: "Networking fundamentals, routing, switching, and network programming basics.",
        equipment: ["To be updated"],
      },
    ],
    activities: ["Technical club events (to be updated)", "Hackathons/Workshops (to be updated)"],
    downloads: [
      { label: "Syllabus", href: "/syllabus" },
      { label: "Academic Calendar", href: "/calendar" },
    ],
    careers: [
      "Software Engineer / Full Stack Developer",
      "System / Network Engineer",
      "Cloud / DevOps Associate",
      "Competitive Programming & Research",
    ],
  },
  aiml: {
    slug: "aiml",
    short: "AI & ML",
    title: "AI & Machine Learning (AI & ML)",
    bannerImage: "https://images.unsplash.com/photo-1677442136019-21780ecad995?q=80&w=2070&auto=format&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1620712948343-0056911f1462?q=80&w=2070&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1555949963-aa79dcee981c?q=80&w=2070&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1518932945647-7a36269d4cd3?q=80&w=2070&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?q=80&w=2070&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1535223289827-42f1e9919769?q=80&w=2070&auto=format&fit=crop"
    ],
    subtitle: "Outstanding learning environment for excellence in AI and Data Science.",
    program: { name: "B.Tech", duration: "4 Years", intake: "60" },
    hod: { name: "Dr. Kumari Priyanka Sinha", email: "hodcse@ncechandi.ac.in" },
    about:
      "The field of Artificial Intelligence & Machine Learning nowadays has become one of the most demandable branch amongst the aspiring engineers. We have a goal to provide an outstanding learning environment complemented by excellence in teaching. The Department is moving ahead to build technical platform to students by spreading awareness of technologies, transferring of the knowledge, sharpening the obtained knowledge, and exposing students to solve real time problems. Laboratories are fully equipped with latest computers and are supported by high speed Internet connection. Job opportunities are available both in private and public sectors for a graduate of this discipline. Subjects of further research include Artificial Intelligence especially Neural Network and Machine Learning and many more.",
    vision:
      "To become a centre of excellence in Artificial Intelligence & Machine Learning by providing a holistic approach towards research, innovation, entrepreneurship and employability empowered with ethical values.",
    mission: [
      "M1: Mould the students to become AI/ML Professionals, Researchers and Entrepreneurs by providing advanced laboratories.",
      "M2: Impart high quality professional training to get expertise in modern AI tools and ML technologies to cater to the real time requirements of the industry.",
      "M3: Inculcate team work and lifelong learning among students with a sense of societal and ethical responsibilities.",
    ],
    peos: [
      "PEO1: Prepare graduates to have knowledge and skill to compete for career in Artificial Intelligence and Machine Learning.",
      "PEO2: Well qualified to participate in research and innovation in the field of intelligent systems.",
      "PEO3: To train students with good knowledge along with practical efficiency in AI/ML to create novel products for the benefits of life.",
      "PEO4: Develop engineering design skill, problem solving skill and aptitude for innovation in data-driven systems.",
      "PEO5: Graduates will possess leadership qualities, work harmoniously as a team member with effective communication skills.",
    ],
    pos: [
      "PO1: Engineering knowledge",
      "PO2: Problem analysis",
      "PO3: Design/development of solutions",
      "PO4: Conduct investigations of complex problems",
      "PO5: Modern tool usage",
      "PO6: The engineer and society",
      "PO7: Environment and sustainability",
      "PO8: Ethics",
      "PO9: Individual and team work",
      "PO10: Communication",
      "PO11: Project management and finance",
      "PO12: Life-long learning",
    ],
    psos: [
      "PSO1: Foundation of Intelligent System concepts: To use mathematical methodologies to crack problem using suitable machine learning techniques, data structure and suitable algorithm.",
      "PSO2: Foundation of AI & Data Engineering: the ability to interpret the fundamental concepts and methodology of AI systems. Students can understand the functionality of hardware and software aspects of AI systems.",
      "PSO3: Foundations of AI based Software development: the ability to grasp the software development lifecycle for intelligent systems. Possess competent skills and knowledge of AI design process. Familiarity and practical proficiency with a broad area of deep learning concepts.",
    ],
    highlights: [
      "Machine Learning & Deep Learning",
      "Computer Vision & NLP",
      "Data Engineering basics",
      "Responsible AI basics",
    ],
    labs: [
      { name: "AI/ML Lab", desc: "Model building, training workflows, and experimentation.", equipment: ["To be updated"] },
      { name: "Data Science Lab", desc: "Data analysis, visualization, and applied ML pipelines.", equipment: ["To be updated"] },
      { name: "Compute Facility", desc: "GPU/compute resources (as available).", equipment: ["To be updated"] },
      { name: "Mini Project Lab", desc: "Project development and demos.", equipment: ["To be updated"] },
    ],
    activities: ["Project showcases (to be updated)", "AI workshops (to be updated)"],
    downloads: [
      { label: "Syllabus", href: "/syllabus" },
      { label: "Research", href: "/research" },
    ],
    careers: [
      "ML Engineer (entry-level)",
      "Data Analyst / Junior Data Scientist",
      "AI Research Intern",
      "M.Tech / Higher Studies",
    ],
  },
  ce: {
    slug: "ce",
    short: "CE",
    title: "Civil Engineering",
    bannerImage: "https://images.unsplash.com/photo-1541888946425-d81bb19480c5?q=80&w=2070&auto=format&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1504307651254-35680f35aa37?q=80&w=2070&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1531834685032-c34bf0d84c77?q=80&w=2070&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1503387762-592deb58ef4e?q=80&w=2070&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1581094722883-9b19dfb1d283?q=80&w=2070&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1509391366360-1f9509ce1573?q=80&w=2070&auto=format&fit=crop"
    ],
    subtitle: "Excellence in structural design, planning, and infrastructure development.",
    program: { name: "B.Tech", duration: "4 Years", intake: "60" },
    hod: { name: "Sudeep Kumar", email: "sudeep.2k7@gmail.com" },
    about:
      "The field of civil engineering is developing steadily in recent years as we have now realized the importance of infrastructure development. If one has a crave for structural design, planning and construction, then this is the course to be explored. It includes study in the areas of Surveying, Geotechnical Engineering, Structural Engineering, Transportation Engineering, Irrigation & Water Resource Engineering and many more. The department aims to provide better education in the field of Civil Engineering to meet the ever growing construction industry and is dedicated to maintain highest quality in teaching both theoretically and practically and also train the young engineers equipped with latest knowledge in the field of Civil Engineering by providing conductive teaching environment in the classrooms followed by practical training in the relevant laboratory to have hands on experience on the concerned topic.",
    vision:
      "To excel in all streams of civil engineering in technical education, industrial exposure, quality research and innovation.",
    mission: [
      "Provide quality technical education and research guidance consistent with the changing technologies.",
      "Develop excellent infrastructure and laboratories with latest equipment’s.",
      "To get the programme NBA accredited.",
      "Undertake collaborative projects with industries and premier institutes to inculcate an atmosphere for research, innovation and entrepreneurship.",
      "To develop a positive attitude of ethics and social responsibility towards society and environment.",
    ],
    peos: [
      "PEO1: To prepare graduates who will be successful professionals in industry, government, academia, research, entrepreneurial pursuit and consulting firms.",
      "PEO2: To prepare graduates who will contribute to society as broadly educated, expressive, ethical and responsible citizens with proven expertise.",
      "PEO3: Graduates will adopt ethical attitude and exhibit effective skills in communication, management, teamwork and leadership qualities.",
    ],
    pos: [
      "PO1: Engineering knowledge",
      "PO2: Problem analysis",
      "PO3: Design/development of solutions",
      "PO4: Conduct investigations of complex problems",
      "PO5: Modern tool usage",
      "PO6: The engineer and society",
      "PO7: Environment and sustainability",
      "PO8: Ethics",
      "PO9: Individual and team work",
      "PO10: Communication",
      "PO11: Project management and finance",
      "PO12: Life-long learning",
    ],
    psos: [
      "PSO1: Engineering Proficiency: Capability to apply knowledge of mathematics, science, and engineering to solve complex civil engineering problems.",
      "PSO2: Design & Analysis: Ability to design and evaluate civil engineering systems including structures, geotechnical foundations, and transportation networks.",
      "PSO3: Professional Practice: Competence in using modern engineering tools and techniques for sustainable infrastructure development and project management.",
    ],
    highlights: [
      "Structural Analysis & Design",
      "Surveying & Geomatics",
      "Transportation Engineering",
      "Environmental Engineering",
    ],
    labs: [
      { name: "Survey Lab", desc: "Surveying instruments and field practice.", equipment: ["To be updated"] },
      { name: "Concrete & Material Testing Lab", desc: "Material testing and mix design practices.", equipment: ["To be updated"] },
      { name: "Geotechnical Lab", desc: "Soil testing and foundation engineering experiments.", equipment: ["To be updated"] },
      { name: "Environmental Engineering Lab", desc: "Water/wastewater basics and environmental studies.", equipment: ["To be updated"] },
    ],
    activities: ["Site visits (to be updated)", "Model making / workshops (to be updated)"],
    downloads: [
      { label: "Syllabus", href: "/syllabus" },
      { label: "Notices", href: "/notices" },
    ],
    careers: [
      "Site Engineer / QA-QC",
      "Structural Design (entry-level)",
      "Govt. Sector / PSU preparation",
      "Higher Studies & Research",
    ],
  },
  me: {
    slug: "me",
    short: "ME",
    title: "Mechanical Engineering",
    bannerImage: "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?q=80&w=2070&auto=format&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1565439387814-23eb4be684ce?q=80&w=2070&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1535402803947-a950d5f7fa47?q=80&w=2070&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1581092160562-40aa08e78837?q=80&w=2070&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1581092334651-ddf26d9a09d0?q=80&w=2070&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1605272186985-e11f1857c5a0?q=80&w=2070&auto=format&fit=crop"
    ],
    subtitle: "Focus on design, manufacturing, thermal sciences, and robotics.",
    program: { name: "B.Tech", duration: "4 Years", intake: "60" },
    hod: { name: "Dr. Md. Zishanur Rahman", email: "rzishan10@gmail.com" },
    about:
      "The branch of Mechanical Engineering is considered to be one of the oldest and broadest engineering discipline. The scope of the course varies from material research to machinery development, Nano Technology, Smart materials, Aerospace Technology, FMS, Automation and such other interrelated developments. Ample job opportunities are open for Mechanical Engineers in Aerospace, Automotive and Manufacturing sectors apart from research establishments. The areas of study include Manufacturing processes, Mechatronics, Heat and Mass Transfer, Tool Engineering and Design, Design of machine elements, CIM and Robotic. We aim to bridge the gap between industry and educational institution, and for this we have qualified faculties and labs with modern testing machines and equipment’s to cope up with advanced technologies.",
    vision:
      "To be the centre of excellence in the field of Mechanical Engineering in the state, where, the budding graduates should have sound technical knowledge and entrepreneurship skills to cater the needs of industry and social responsibilities with good moral value and ethics.",
    mission: [
      "Impart the best quality education to the students where students can pursue their career goals.",
      "To develop collaboration with prestigious Institutions and Industries.",
      "To provide an effective academic environment to the students coupled with ethics and leadership skills.",
    ],
    peos: [
      "PEO1: Graduates should have strong fundamentals in mathematics, science and engineering in order to solve a wide range of technical problem.",
      "PEO2: To motivate the students to continuously improve themselves in Research areas and knowledge of new technologies for research and higher education.",
      "PEO3: To promote awareness among the students about the importance of creativity and innovation in the field of multidiscipline area of engineering.",
    ],
    pos: [
      "PO1: Engineering knowledge",
      "PO2: Problem analysis",
      "PO3: Design/development of solutions",
      "PO4: Conduct investigations of complex problems",
      "PO5: Modern tool usage",
      "PO6: The engineer and society",
      "PO7: Environment and sustainability",
      "PO8: Ethics",
      "PO9: Individual and team work",
      "PO10: Communication",
      "PO11: Project management and finance",
      "PO12: Life-long learning",
    ],
    psos: [
      "PSO1: Mechanical Design: Ability to design and analyze mechanical systems including machinery development, robotics, and smart materials.",
      "PSO2: Thermal & Fluid Systems: Competence in thermal sciences, heat and mass transfer, and their applications in aerospace and automotive technologies.",
      "PSO3: Manufacturing & Automation: Capability to apply modern manufacturing processes, nano technology, and automation for industrial excellence.",
    ],
    highlights: [
      "Thermodynamics & Heat Transfer",
      "Manufacturing Processes",
      "Machine Design",
      "CAD/CAM basics",
    ],
    labs: [
      { name: "Thermal Engineering Lab", desc: "Thermal systems experiments and measurements.", equipment: ["To be updated"] },
      { name: "Manufacturing / Workshop", desc: "Hands-on workshop practice and manufacturing basics.", equipment: ["To be updated"] },
      { name: "CAD Lab", desc: "CAD modelling and engineering drawing tools.", equipment: ["To be updated"] },
      { name: "Metrology Lab", desc: "Measurements, tolerances, and quality inspection basics.", equipment: ["To be updated"] },
    ],
    activities: ["Workshops (to be updated)", "Industrial visits (to be updated)"],
    downloads: [
      { label: "Syllabus", href: "/syllabus" },
      { label: "Placements", href: "/placement" },
    ],
    careers: [
      "Production / Maintenance Engineer",
      "Design Engineer (entry-level)",
      "Automotive & Core Mechanical",
      "Higher Studies / GATE",
    ],
  },
  aero: {
    slug: "aero",
    short: "AERO",
    title: "Aeronautical Engineering",
    bannerImage: "https://images.unsplash.com/photo-1517976487492-5750f3195933?q=80&w=2070&auto=format&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1436491865332-7a61a109cc05?q=80&w=2070&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1540962351504-03099e0a754b?q=80&w=2070&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1506012787146-f92b2d7d6d96?q=80&w=2070&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1621570776935-43a9f0a0c9ee?q=80&w=2070&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1559685603-91db48d1c7f0?q=80&w=2070&auto=format&fit=crop"
    ],
    subtitle: "Center of excellence in Aeronautics, Propulsion & Aircraft Design.",
    program: { name: "B.Tech", duration: "4 Years", intake: "60" },
    hod: { name: "Dr. Alok Kumar", email: "alokbpsc2018@gmail.com" },
    about:
      "The Department of Aeronautical Engineering at NCE Chandi focuses on the design, development, and maintenance of aircraft and spacecraft. It covers core areas like Aerodynamics, Propulsion, Aircraft Structures, and Flight Mechanics. The department aims to produce skilled aerospace engineers capable of contributing to the aviation and defense sectors through theoretical excellence and practical lab training.",
    vision:
      "To be a premier center of excellence in Aeronautical Engineering, producing innovators and researchers who lead the aerospace industry with technical expertise and ethical values.",
    mission: [
      "Provide high-quality education in aerospace technologies through advanced infrastructure.",
      "Foster a research-oriented environment to address complex challenges in flight and space exploration.",
      "Cultivate entrepreneurship and leadership skills among students for global competitiveness.",
      "Maintain strong industry-academia ties for practical exposure and placement.",
    ],
    peos: [
      "PEO1: Graduates will be successful in core aeronautical engineering and related multidisciplinary fields.",
      "PEO2: Graduates will possess the ability to solve complex technical problems in the aerospace sector.",
      "PEO3: Graduates will demonstrate professional ethics and lifelong learning in their careers.",
    ],
    pos: [
      "PO1: Engineering knowledge",
      "PO2: Problem analysis",
      "PO3: Design/development of solutions",
      "PO4: Conduct investigations of complex problems",
      "PO5: Modern tool usage",
      "PO6: The engineer and society",
      "PO7: Environment and sustainability",
      "PO8: Ethics",
      "PO9: Individual and team work",
      "PO10: Communication",
      "PO11: Project management and finance",
      "PO12: Life-long learning",
    ],
    psos: [
      "PSO1: Aerodynamics & Design: Ability to design and analyze aerodynamic shapes and flight configurations.",
      "PSO2: Propulsion & Structures: Competence in aircraft engines, propulsion systems, and structural integrity.",
      "PSO3: Flight Technology: Capability to use modern simulation and testing tools for aircraft performance evaluation.",
    ],
    highlights: [
      "Aerodynamics fundamentals",
      "Aircraft Structures",
      "Propulsion basics",
      "Flight Mechanics basics",
    ],
    labs: [
      { name: "Aerodynamics Lab", desc: "Aerodynamics experiments (as available).", equipment: ["To be updated"] },
      { name: "Structures / Materials Lab", desc: "Material properties and structures basics.", equipment: ["To be updated"] },
      { name: "CAD / Design Lab", desc: "Design tools for aircraft modelling basics.", equipment: ["To be updated"] },
      { name: "Project & Model Lab", desc: "Prototype/model building and project showcase.", equipment: ["To be updated"] },
    ],
    activities: ["Model/Aeromodelling activities (to be updated)", "Seminars (to be updated)"],
    downloads: [
      { label: "Syllabus", href: "/syllabus" },
      { label: "Research", href: "/research" },
    ],
    careers: [
      "Aerospace / Aviation (entry-level roles)",
      "Design & Analysis (entry-level)",
      "Defence sector preparation",
      "Higher Studies & Research",
    ],
  },
  eee: {
    slug: "eee",
    short: "EEE",
    title: "Electrical & Electronics Engineering (EEE)",
    bannerImage: "https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?q=80&w=2070&auto=format&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1581093458791-9f3c3900df4b?q=80&w=2070&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1518770660439-4636190af475?q=80&w=2070&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1555664424-778a1e5e1b48?q=80&w=2070&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1581092921461-eab62e97a780?q=80&w=2070&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1517420704952-d9f39741e815?q=80&w=2070&auto=format&fit=crop"
    ],
    subtitle: "Innovation in power systems, control, and electronics.",
    program: { name: "B.Tech", duration: "4 Years", intake: "60" },
    hod: { name: "Ashish Kumar", email: "ashishashish29@gmail.com" },
    about:
      "This is a new branch which provides integration of Electrical and Electronics engineering. The major thrust in this course is related to the basic principles and detailed analysis of equipment’s and systems for generation, transmission, distribution and utilization of electrical energy. The department is committed to engage in high quality research and pursuit of excellence in teaching. The faculty members of the department are actively involved in research and development in challenging areas of both theory and experiment. The labs established here have been well equipped with the latest equipment. Instructional laboratories for Basic Electronics, Analog Electronics and Digital Electronics are fully operational.",
    vision:
      "To be recognized as an efficient center of Electrical and Electronics Engineering striving to propel the pace of nation’s socio-economic development through excellence in technological innovation and research.",
    mission: [
      "M1. To provide an opportunity to master engineering and technology through interaction with local environment.",
      "M2. To focus on emerging technologies to fulfill local demands ensuring global standards.",
      "M3. To meet international industrial standards by integrating emerging technologies in the infancy stage with the existing advanced technologies.",
      "M4. To create various opportunities for entrepreneurs and business enterprises for new product development by providing innovative solutions to technological problems, thus facilitating socio-economic growth.",
    ],
    peos: [
      "PEO1: Develop skills and proficiency in core areas of Electrical and Electronics related multidisciplinary Engineering fundamentals.",
      "PEO2: Demonstrate technical competence to tackle problems in the field of industry using emerging technologies, innovation and entrepreneur skill.",
      "PEO3: Pursue higher education, research and development in electrical engineering and allied areas of science and technology.",
    ],
    pos: [
      "PO1: Engineering knowledge",
      "PO2: Problem analysis",
      "PO3: Design/development of solutions",
      "PO4: Conduct investigations of complex problems",
      "PO5: Modern tool usage",
      "PO6: The engineer and society",
      "PO7: Environment and sustainability",
      "PO8: Ethics",
      "PO9: Individual and team work",
      "PO10: Communication",
      "PO11: Project management and finance",
      "PO12: Life-long learning",
    ],
    psos: [
      "PSO1: Develop sustainable solutions for real; time applications.",
      "PSO2: Demonstrate their knowledge in analysis and design for utilizing renewable energy sources.",
      "PSO3: Analyze, estimate to solve complex problems and meet the challenges in the communication domain.",
    ],
    highlights: [
      "Electrical Machines",
      "Power Systems & Protection",
      "Control Systems",
      "Power Electronics basics",
    ],
    labs: [
      { name: "Electrical Machines Lab", desc: "DC/AC machines experiments and characteristics.", equipment: ["To be updated"] },
      { name: "Power Electronics Lab", desc: "Converters, inverters, and drives basics.", equipment: ["To be updated"] },
      { name: "Control Systems Lab", desc: "Control experiments and system response studies.", equipment: ["To be updated"] },
      { name: "Measurements & Instrumentation Lab", desc: "Measuring instruments and instrumentation basics.", equipment: ["To be updated"] },
    ],
    activities: ["Workshops (to be updated)", "Industrial visits (to be updated)"],
    downloads: [
      { label: "Syllabus", href: "/syllabus" },
      { label: "Placement", href: "/placement" },
    ],
    careers: [
      "Electrical Engineer (entry-level)",
      "Power Sector / Utilities",
      "Automation / Control (entry-level)",
      "Higher Studies / GATE",
    ],
  },
  "mtech-cse": {
    slug: "mtech-cse",
    short: "M.Tech CSE",
    title: "M.Tech in Computer Science & Engineering",
    bannerImage: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?q=80&w=2070&auto=format&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1558494949-ef010968d7f4?q=80&w=2070&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1516116216624-53e697fedbea?q=80&w=2070&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1534972195531-d756b9bfa9f2?q=80&w=2070&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1510915228340-29c85a43dcfe?q=80&w=2070&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1555099962-41decfa6670b?q=80&w=2070&auto=format&fit=crop"
    ],
    subtitle: "Advanced study of algorithms, machine learning, and high performance computing.",
    program: { name: "M.Tech", duration: "2 Years", intake: "30" },
    hod: { name: "Dr. Kumari Priyanka Sinha", email: "hodcse@ncechandi.ac.in" },
    about:
      "The M.Tech in Computer Science & Engineering focuses on advanced research and specialized knowledge in modern computing fields, building upon the department's goal to provide an outstanding learning environment complemented by excellence in teaching.",
    vision:
      "To become a centre of excellence in computer science and engineering by providing a holistic approach towards research, innovation, entrepreneurship and employability empowered with ethical values.",
    mission: [
      "M1: Mould the students to become Software Professionals, Researchers and Entrepreneurs by providing advanced laboratories.",
      "M2: Impart high quality professional training to get expertise in modern software tools and technologies to cater to the real time requirements of the industry.",
      "M3: Inculcate team work and lifelong learning among students with a sense of societal and ethical responsibilities.",
    ],
    peos: [
      "PEO1: Prepare graduates to have knowledge and skill to compete for career in computer science and engineering.",
      "PEO2: Well qualified to participate in research and innovation. Also serve the society with new ideas and be a long-life learner.",
      "PEO3: To train students with good knowledge along with practical efficiency in computer science to create novel products for the benefits of life.",
      "PEO4: Develop engineering design skill, problem solving skill and aptitude for innovation as they work individually and in multidisciplinary area.",
      "PEO5: Graduates will possess leadership qualities, work harmoniously as a team member with effective communication skills.",
    ],
    pos: ["To be updated."],
    psos: ["To be updated."],
    highlights: ["Advanced Algorithms", "Machine Learning Research", "High Performance Computing", "Dissertation & Projects"],
    labs: [
      { name: "PG Research Lab", desc: "Dedicated research facility for M.Tech students.", equipment: ["High-end workstations", "Cloud compute access"] },
    ],
    activities: ["Research Seminars", "Journal Publications", "Workshops"],
    downloads: [{ label: "Syllabus", href: "/syllabus" }],
    careers: ["Research Engineer", "Data Scientist", "System Architect", "Higher Studies (Ph.D)"],
  },
  "mtech-ps": {
    slug: "mtech-ps",
    short: "M.Tech PS",
    title: "M.Tech in Power Systems",
    bannerImage: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=80&w=2070&auto=format&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?q=80&w=2070&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1581093458791-9f3c3900df4b?q=80&w=2070&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1621905251189-08b45d6a269e?q=80&w=2070&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1505751172876-fa1923c5c528?q=80&w=2070&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1581093259461-1ca04f0952da?q=80&w=2070&auto=format&fit=crop"
    ],
    subtitle: "In-depth study of electrical power systems, smart grids, and renewable energy integration.",
    program: { name: "M.Tech", duration: "2 Years", intake: "30" },
    hod: { name: "To be updated", email: "hodeee@ncechandi.ac.in" },
    about: "The M.Tech in Power Systems offers specialized training in modern power grids, protection systems, and energy management, preparing students for leadership roles in the energy sector.",
    vision: "To be updated.",
    mission: ["To be updated."],
    peos: ["To be updated."],
    pos: ["To be updated."],
    psos: ["To be updated."],
    highlights: ["Smart Grid Technology", "Power System Protection", "Renewable Energy integration", "Power Electronics in PS"],
    labs: [
      { name: "Advanced Power Systems Lab", desc: "Specialized lab for power system simulation and testing.", equipment: ["Simulation tools", "Relay testing kits"] },
    ],
    activities: ["Technical seminars", "Industry collaboration", "Research project work"],
    downloads: [{ label: "Syllabus", href: "/syllabus" }],
    careers: ["Power System Analyst", "Smart Grid Specialist", "Energy Consultant", "Academic / Research roles"],
  },
};

export const DEPARTMENT_LIST = Object.values(DEPARTMENTS);

export const SLUG_ALIASES = {
  "ai-ml": "aiml",
  "ai_ml": "aiml",
  "ai&ml": "aiml",
  "aiandml": "aiml",
  "ai-ml-engineering": "aiml",
  "artificial-intelligence": "aiml",
  "artificial-intelligence-and-ml": "aiml",
  "artificial-intelligence-and-machine-learning": "aiml",

  cse: "cse",
  "computer-science": "cse",
  "computer-science-engineering": "cse",
  "computer-science-and-engineering": "cse",

  aeronautical: "aero",
  "aeronautical-engineering": "aero",
  aeroengineering: "aero",

  mechanical: "me",
  machenical: "me",
  "mechanical-engineering": "me",
  mechanicalengineering: "me",
  mech: "me",

  civil: "ce",
  "civil-engineering": "ce",

  "electrical-and-electronics": "eee",
  "electrical-electronics": "eee",
  electrical: "eee",
  "electrical-engineering": "eee",
  "eee-department": "eee",

  "mtech-cse": "mtech-cse",
  "m-tech-cse": "mtech-cse",
  "pg-cse": "mtech-cse",
  "mtech-power-systems": "mtech-ps",
  "m-tech-power-systems": "mtech-ps",
  "pg-power-systems": "mtech-ps",
};
      
