export const principal = {
  name: "Dr. Gopal Nandan",
  designation: "Principal",
  department: "Nalanda College of Engineering, Chandi",
  qualification: "Ph.D.",
  email: "nceprincipalchandi@gmail.com",
  phone: "+91-9412955789",
  office: "Principal Office",
  areas: ["Administration", "Academic Leadership"],
  photo: null,
};

export const facultyDepartments = [
  {
    key: "cse",
    title: "Computer Science & Engineering",
    head: {
      name: "Dr. Kumari Priyanka Sinha",
      designation: "Assistant Professor & Head",
      department: "Computer Science & Engineering",
      qualification: "Ph.D.",
      email: "hodcse@ncechandi.ac.in",
      phone: "+91-XXXXXXXXXX",
      office: "CSE Department",
      areas: ["Software Engineering", "Cloud Computing"],
      photo: null,
    },
    assistants: [
      {
        name: "Digember Kumar",
        designation: "Assistant Professor",
        department: "Computer Science & Engineering",
        qualification: "M.Tech.",
        email: "digember.kumar85@gmail.com",
        phone: "+91-9579334914",
        office: "CSE Department",
        areas: ["Systems", "Programming"],
        photo: null,
      },
      {
        name: "Dr. SAKSHIWALA",
        designation: "Assistant Professor",
        department: "Computer Science & Engineering",
        qualification: "Ph.D.",
        email: "sakshiwala2022@gmail.com",
        phone: "+91-9705632100",
        office: "CSE Department",
        areas: ["Computer Networks", "Information Security"],
        photo: null,
      },
      {
        name: "Rajeev Kumar",
        designation: "Assistant Professor",
        department: "Computer Science & Engineering",
        qualification: "M.Tech.",
        email: "ap.rajeev@ncechandi.ac.in",
        phone: "+91-XXXXXXXXXX",
        office: "CSE Department",
        areas: ["Digital Logic", "Compilers"],
        photo: null,
      },
      {
        name: "Rashmi Sinha",
        designation: "Assistant Professor",
        department: "Computer Science & Engineering",
        qualification: "M.Tech.",
        email: "nanhualok@gmail.com",
        phone: "+91-7903262170",
        office: "CSE Department",
        areas: ["Database Management Systems"],
        photo: null,
      },
      {
        name: "Kumar Sachin Yadav",
        designation: "Assistant Professor",
        department: "Computer Science & Engineering",
        qualification: "M.Tech.",
        email: "sachinkumar02144@gmail.com",
        phone: "+91-9122710072",
        office: "CSE Department",
        areas: ["Algorithms", "Data structures"],
        photo: null,
      },
      {
        name: "Kumari Shambhavi",
        designation: "Assistant Professor",
        department: "Computer Science & Engineering",
        qualification: "M.Tech.",
        email: "shambhavinitp1993@gmail.com",
        phone: "+91-7065725154",
        office: "CSE Department",
        areas: ["Artificial Intelligence", "Theory of Computation"],
        photo: null,
      },
    ],
  },
  {
    key: "aiml",
    title: "Artificial Intelligence & ML",
    head: {
      name: "Dr. Kumari Priyanka Sinha",
      designation: "Assistant Professor & Head",
      department: "Artificial Intelligence & ML",
      qualification: "Ph.D.",
      email: "hodcse@ncechandi.ac.in",
      phone: "+91-XXXXXXXXXX",
      office: "AI & ML Department",
      areas: ["Software Engineering", "Cloud Computing"],
      photo: null,
    },
    assistants: [
      {
        name: "Digember Kumar",
        designation: "Assistant Professor",
        department: "Artificial Intelligence & ML",
        qualification: "M.Tech.",
        email: "digember.kumar85@gmail.com",
        phone: "+91-9579334914",
        office: "AI & ML Department",
        areas: ["Systems", "Programming"],
        photo: null,
      },
      {
        name: "Dr. SAKSHIWALA",
        designation: "Assistant Professor",
        department: "Artificial Intelligence & ML",
        qualification: "Ph.D.",
        email: "sakshiwala2022@gmail.com",
        phone: "+91-9705632100",
        office: "AI & ML Department",
        areas: ["Computer Networks", "Information Security"],
        photo: null,
      },
      {
        name: "Rajeev Kumar",
        designation: "Assistant Professor",
        department: "Artificial Intelligence & ML",
        qualification: "M.Tech.",
        email: "ap.rajeev@ncechandi.ac.in",
        phone: "+91-XXXXXXXXXX",
        office: "AI & ML Department",
        areas: ["Digital Logic", "Compilers"],
        photo: null,
      },
      {
        name: "Rashmi Sinha",
        designation: "Assistant Professor",
        department: "Artificial Intelligence & ML",
        qualification: "M.Tech.",
        email: "nanhualok@gmail.com",
        phone: "+91-7903262170",
        office: "AI & ML Department",
        areas: ["Database Management Systems"],
        photo: null,
      },
      {
        name: "Kumar Sachin Yadav",
        designation: "Assistant Professor",
        department: "Artificial Intelligence & ML",
        qualification: "M.Tech.",
        email: "sachinkumar02144@gmail.com",
        phone: "+91-9122710072",
        office: "AI & ML Department",
        areas: ["Algorithms", "Data structures"],
        photo: null,
      },
      {
        name: "Kumari Shambhavi",
        designation: "Assistant Professor",
        department: "Artificial Intelligence & ML",
        qualification: "M.Tech.",
        email: "shambhavinitp1993@gmail.com",
        phone: "+91-7065725154",
        office: "AI & ML Department",
        areas: ["Artificial Intelligence", "Theory of Computation"],
        photo: null,
      },
    ],
  },
  {
    key: "ce",
    title: "Civil Engineering",
    head: {
      name: "Sudeep Kumar",
      designation: "Assistant Professor & Head",
      department: "Civil Engineering",
      qualification: "M.Tech.",
      email: "sudeep.2k7@gmail.com",
      phone: "+91-7903026264",
      office: "Civil Engineering Department",
      areas: ["Planning & Construction", "Structural Design"],
      photo: null,
    },
    assistants: [
      {
        name: "Bhawesh Madhukar",
        designation: "Assistant Professor",
        department: "Civil Engineering",
        qualification: "M.Tech.",
        email: "nce.hodcivil@gmail.com",
        phone: "+91-9716416402",
        office: "Civil Engineering Department",
        areas: ["Surveying", "Geotechnical Engineering"],
        photo: null,
      },
      {
        name: "Dr. Keshav Kumar",
        designation: "Assistant Professor",
        department: "Civil Engineering",
        qualification: "Ph.D.",
        email: "keshav151008@nitp.ac.in",
        phone: "+91-8797034365",
        office: "Civil Engineering Department",
        areas: ["Hydraulics", "Water Resource Engineering"],
        photo: null,
      },
      {
        name: "Mansi Ranjan",
        designation: "Assistant Professor",
        department: "Civil Engineering",
        qualification: "M.Tech.",
        email: "mansiranjan25@gmail.com",
        phone: "+91-9135851509",
        office: "Civil Engineering Department",
        areas: ["Transportation Engineering", "Surveying"],
        photo: null,
      },
      {
        name: "Akash Ranjan",
        designation: "Assistant Professor",
        department: "Civil Engineering",
        qualification: "M.Tech.",
        email: "akashranjan664@gmail.com",
        phone: "+91-7978033855",
        office: "Civil Engineering Department",
        areas: ["Building Construction", "CAD"],
        photo: null,
      },
      {
        name: "Supriya Sinha",
        designation: "Assistant Professor",
        department: "Civil Engineering",
        qualification: "M.Tech.",
        email: "ap.supriya@ncechandi.ac.in",
        phone: "+91-7870763487",
        office: "Civil Engineering Department",
        areas: ["Irrigation & Water Resource Engineering"],
        photo: null,
      },
    ],
  },
  {
    key: "me",
    title: "Mechanical Engineering",
    head: {
      name: "Dr. Md. Zishanur Rahman",
      designation: "Assistant Professor and HOD",
      department: "Mechanical Engineering",
      qualification: "Ph.D.",
      email: "rzishan10@gmail.com",
      phone: "+91-7903936822",
      office: "Mechanical Engineering Department",
      areas: ["Machinery Development", "Robotics", "Design"],
      photo: null,
    },
    assistants: [
      {
        name: "Avinash Kumar",
        designation: "Assistant Professor",
        department: "Mechanical Engineering",
        qualification: "M.Tech.",
        email: "kumaravinash858@gmail.com",
        phone: "+91-XXXXXXXXXX",
        office: "Mechanical Engineering Department",
        areas: ["Manufacturing Processes", "Tool Engineering"],
        photo: null,
      },
      {
        name: "Saurabh Suman",
        designation: "Assistant Professor",
        department: "Mechanical Engineering",
        qualification: "M.Tech.",
        email: "s.sumansliet@gmail.com",
        phone: "+91-7674924892",
        office: "Mechanical Engineering Department",
        areas: ["Mechatronics", "Heat and Mass Transfer", "CIM"],
        photo: null,
      },
    ],
  },
  {
    key: "aero",
    title: "Aeronautical Engineering",
    head: {
      name: "Dr. Alok Kumar",
      designation: "Assistant Professor and HOD",
      department: "Aeronautical Engineering",
      qualification: "Ph.D.",
      email: "alokbpsc2018@gmail.com",
      phone: "+91-9576288028",
      office: "Aeronautical Engineering Department",
      areas: ["Aerodynamics", "Aerospace Design"],
      photo: null,
    },
    assistants: [
      {
        name: "Prabhakar kumar",
        designation: "Assistant Professor",
        department: "Aeronautical Engineering",
        qualification: "M.Tech.",
        email: "aero805pkumar@gmail.com",
        phone: "+91-7257029251",
        office: "Aeronautical Engineering Department",
        areas: ["Flight Mechanics", "Aircraft Structures"],
        photo: null,
      },
      {
        name: "Rajnish Kumar",
        designation: "Assistant Professor",
        department: "Aeronautical Engineering",
        qualification: "M.Tech.",
        email: "agrajnish@gmail.com",
        phone: "+91-7258066388",
        office: "Aeronautical Engineering Department",
        areas: ["Propulsion", "Space Technologies"],
        photo: null,
      },
    ],
  },
  {
    key: "eee",
    title: "Electrical & Electronics Engineering",
    head: {
      name: "Ashish Kumar",
      designation: "Assistant Professor & Head",
      department: "Electrical & Electronics Engineering",
      qualification: "M.Tech.",
      email: "ashishashish29@gmail.com",
      phone: "+91-XXXXXXXXXX",
      office: "EEE Department",
      areas: ["Generation", "Transmission"],
      photo: null,
    },
    assistants: [
      {
        name: "Varun Kumar",
        designation: "Assistant Professor",
        department: "Electrical & Electronics Engineering",
        qualification: "M.Tech.",
        email: "svnitvarun28@gmail.com",
        phone: "+91-6203785805",
        office: "EEE Department",
        areas: ["Power Systems", "Distribution"],
        photo: null,
      },
      {
        name: "Dr. Tripurari Das Gupta",
        designation: "Assistant Professor",
        department: "Electrical & Electronics Engineering",
        qualification: "Ph.D.",
        email: "tripu008@gmail.com",
        phone: "+91-9557745349",
        office: "EEE Department",
        areas: ["Utilization of Electrical Energy", "Research"],
        photo: null,
      },
      {
        name: "Dr. Md. Tausif Ahmad",
        designation: "Assistant Professor",
        department: "Electrical & Electronics Engineering",
        qualification: "Ph.D.",
        email: "mtahmad16_phd2k11@dtu.ac.in",
        phone: "+91-8076475415",
        office: "EEE Department",
        areas: ["Electrical Energy", "Technological Innovation"],
        photo: null,
      },
      {
        name: "Ashok Kumar Chaudhary",
        designation: "Assistant Professor",
        department: "Electrical & Electronics Engineering",
        qualification: "M.Tech.",
        email: "ak02557@gmail.com",
        phone: "+91-9939930486",
        office: "EEE Department",
        areas: ["Control Systems", "Basic Electronics"],
        photo: null,
      },
      {
        name: "Mona Priya",
        designation: "Assistant Professor",
        department: "Electrical & Electronics Engineering",
        qualification: "M.Tech.",
        email: "ap.mona@ncechandi.ac.in",
        phone: "+91-XXXXXXXXXX",
        office: "EEE Department",
        areas: ["Analog Electronics", "Digital Electronics"],
        photo: null,
      },
      {
        name: "Nikhil Nigam",
        designation: "Assistant Professor",
        department: "Electrical & Electronics Engineering",
        qualification: "M.Tech.",
        email: "nikhil.nigam07@gmail.com",
        phone: "+91-8309954480",
        office: "EEE Department",
        areas: ["Electrical Systems", "Communication Domain"],
        photo: null,
      },
      {
        name: "Dr. Shagufta Khan",
        designation: "Assistant Professor",
        department: "Electrical & Electronics Engineering",
        qualification: "Ph.D.",
        email: "khan.shagufta7@gmail.com",
        phone: "+91-8076529164",
        office: "EEE Department",
        areas: ["Renewable Energy Sources", "Sustainable Solutions"],
        photo: null,
      },
      {
        name: "Dr. Sanjay Kumar",
        designation: "Assistant Professor",
        department: "Electrical & Electronics Engineering",
        qualification: "Ph.D.",
        email: "apsanjaynce2024@gmail.com",
        phone: "+91-8789495674",
        office: "EEE Department",
        areas: ["Communication Systems", "Electrical Engineering"],
        photo: null,
      },
    ],
  },
];
