export const principal = {
  name: "Dr. Gopal Nandan",
  designation: "Principal",
  department: "Nalanda College of Engineering, Chandi",
  qualification: "Ph.D.",
  email: "principal@ncechandi.ac.in",
  phone: "+91-XXXXXXXXXX",
  office: "Principal Office",
  areas: ["Administration", "Academic Leadership"],
  photo: null,
};

export const facultyDepartments = [
  {
    key: "cse",
    title: "Computer Science & Engineering",
    head: {
      name: "Dr. (HOD Name)",
      designation: "Head of Department",
      department: "Computer Science & Engineering",
      qualification: "Ph.D.",
      email: "hod.cse@ncechandi.ac.in",
      phone: "+91-XXXXXXXXXX",
      office: "CSE Department",
      areas: ["Systems", "Data Science"],
      photo: null,
    },
    assistants: [
      {
        name: "(Faculty Name)",
        designation: "Assistant Professor",
        department: "Computer Science & Engineering",
        qualification: "M.Tech.",
        email: "ap1.cse@ncechandi.ac.in",
        phone: "+91-XXXXXXXXXX",
        office: "CSE Department",
        areas: ["Programming", "DBMS"],
        photo: null,
      },
      {
        name: "(Faculty Name)",
        designation: "Assistant Professor",
        department: "Computer Science & Engineering",
        qualification: "M.Tech.",
        email: "ap2.cse@ncechandi.ac.in",
        phone: "+91-XXXXXXXXXX",
        office: "CSE Department",
        areas: ["Networks", "Security"],
        photo: null,
      },
    ],
  },
  {
    key: "aiml",
    title: "Artificial Intelligence & ML",
    head: {
      name: "Dr. (HOD Name)",
      designation: "Head of Department",
      department: "Artificial Intelligence & ML",
      qualification: "Ph.D.",
      email: "hod.aiml@ncechandi.ac.in",
      phone: "+91-XXXXXXXXXX",
      office: "AI & ML Department",
      areas: ["Machine Learning", "AI Systems"],
      photo: null,
    },
    assistants: [
      {
        name: "(Faculty Name)",
        designation: "Assistant Professor",
        department: "Artificial Intelligence & ML",
        qualification: "M.Tech.",
        email: "ap1.aiml@ncechandi.ac.in",
        phone: "+91-XXXXXXXXXX",
        office: "AI & ML Department",
        areas: ["Deep Learning", "NLP"],
        photo: null,
      },
      {
        name: "(Faculty Name)",
        designation: "Assistant Professor",
        department: "Artificial Intelligence & ML",
        qualification: "M.Tech.",
        email: "ap2.aiml@ncechandi.ac.in",
        phone: "+91-XXXXXXXXXX",
        office: "AI & ML Department",
        areas: ["Computer Vision", "Data Mining"],
        photo: null,
      },
    ],
  },
  {
    key: "ce",
    title: "Civil Engineering",
    head: {
      name: "Dr. (HOD Name)",
      designation: "Head of Department",
      department: "Civil Engineering",
      qualification: "Ph.D.",
      email: "hod.ce@ncechandi.ac.in",
      phone: "+91-XXXXXXXXXX",
      office: "Civil Department",
      areas: ["Structures", "Geotechnical"],
      photo: null,
    },
    assistants: [
      {
        name: "(Faculty Name)",
        designation: "Assistant Professor",
        department: "Civil Engineering",
        qualification: "M.Tech.",
        email: "ap1.ce@ncechandi.ac.in",
        phone: "+91-XXXXXXXXXX",
        office: "Civil Department",
        areas: ["Surveying", "Concrete"],
        photo: null,
      },
      {
        name: "(Faculty Name)",
        designation: "Assistant Professor",
        department: "Civil Engineering",
        qualification: "M.Tech.",
        email: "ap2.ce@ncechandi.ac.in",
        phone: "+91-XXXXXXXXXX",
        office: "Civil Department",
        areas: ["Transportation", "Hydraulics"],
        photo: null,
      },
    ],
  },
  {
    key: "me",
    title: "Mechanical Engineering",
    head: {
      name: "Dr. (HOD Name)",
      designation: "Head of Department",
      department: "Mechanical Engineering",
      qualification: "Ph.D.",
      email: "hod.me@ncechandi.ac.in",
      phone: "+91-XXXXXXXXXX",
      office: "Mechanical Department",
      areas: ["Thermal", "Design"],
      photo: null,
    },
    assistants: [
      {
        name: "(Faculty Name)",
        designation: "Assistant Professor",
        department: "Mechanical Engineering",
        qualification: "M.Tech.",
        email: "ap1.me@ncechandi.ac.in",
        phone: "+91-XXXXXXXXXX",
        office: "Mechanical Department",
        areas: ["Manufacturing", "CAD"],
        photo: null,
      },
      {
        name: "(Faculty Name)",
        designation: "Assistant Professor",
        department: "Mechanical Engineering",
        qualification: "M.Tech.",
        email: "ap2.me@ncechandi.ac.in",
        phone: "+91-XXXXXXXXXX",
        office: "Mechanical Department",
        areas: ["Fluids", "Materials"],
        photo: null,
      },
    ],
  },
  {
    key: "aero",
    title: "Aeronautical Engineering",
    head: {
      name: "Dr. (HOD Name)",
      designation: "Head of Department",
      department: "Aeronautical Engineering",
      qualification: "Ph.D.",
      email: "hod.aero@ncechandi.ac.in",
      phone: "+91-XXXXXXXXXX",
      office: "Aeronautical Department",
      areas: ["Aerodynamics", "Propulsion"],
      photo: null,
    },
    assistants: [
      {
        name: "(Faculty Name)",
        designation: "Assistant Professor",
        department: "Aeronautical Engineering",
        qualification: "M.Tech.",
        email: "ap1.aero@ncechandi.ac.in",
        phone: "+91-XXXXXXXXXX",
        office: "Aeronautical Department",
        areas: ["Structures", "CFD"],
        photo: null,
      },
      {
        name: "(Faculty Name)",
        designation: "Assistant Professor",
        department: "Aeronautical Engineering",
        qualification: "M.Tech.",
        email: "ap2.aero@ncechandi.ac.in",
        phone: "+91-XXXXXXXXXX",
        office: "Aeronautical Department",
        areas: ["Flight Mechanics", "Materials"],
        photo: null,
      },
    ],
  },
  {
    key: "eee",
    title: "Electrical & Electronics Engineering",
    head: {
      name: "Dr. (HOD Name)",
      designation: "Head of Department",
      department: "Electrical & Electronics Engineering",
      qualification: "Ph.D.",
      email: "hod.eee@ncechandi.ac.in",
      phone: "+91-XXXXXXXXXX",
      office: "EEE Department",
      areas: ["Power", "Control"],
      photo: null,
    },
    assistants: [
      {
        name: "(Faculty Name)",
        designation: "Assistant Professor",
        department: "Electrical & Electronics Engineering",
        qualification: "M.Tech.",
        email: "ap1.eee@ncechandi.ac.in",
        phone: "+91-XXXXXXXXXX",
        office: "EEE Department",
        areas: ["Machines", "Electronics"],
        photo: null,
      },
      {
        name: "(Faculty Name)",
        designation: "Assistant Professor",
        department: "Electrical & Electronics Engineering",
        qualification: "M.Tech.",
        email: "ap2.eee@ncechandi.ac.in",
        phone: "+91-XXXXXXXXXX",
        office: "EEE Department",
        areas: ["Power Systems", "IoT"],
        photo: null,
      },
    ],
  },
];
